apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql_image
        imagePullPolicy: Never
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 128Mi
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-disk