apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.222
  selector:
    app: ftps
  ports:
  - name: ftp-connection
    port: 21
  - name: ftp-data
    port: 20021