apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  name: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.222
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 22
    name: ssh
    protocol: TCP
    targetPort: 22
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443